apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-sb-app
spec:
  title: Markdown Sample
  description: A sample workshop using Markdown
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/everythingeverywhere/lab-sb-app
  content:
    image: quay.io/eduk8s/jdk11-environment:latest
    files: github.com/everythingeverywhere/lab-sb-app
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
